import React, { useState } from 'react';
import { AnalyticalReport } from '../../services/types';
import { TariffService } from '../../services/api';
import { toast } from 'react-toastify';

interface Props {
    report: AnalyticalReport;
}

export function TariffDraft({ report }: Props) {
    const [draft, setDraft] = useState<string | null>(null);
    const [loading, setLoading] = useState(false);
    const [isEditing, setIsEditing] = useState(false);
    const [editedDraft, setEditedDraft] = useState('');

    const handleGenerate = async () => {
        setLoading(true);
        try {
            // In a real scenario, these precise controllable/uncontrollable gaps would come from the engine.
            // We map the available mock/engine data from the AnalyticalReport.
            const response = await TariffService.generateDraft({
                financial_year: report.financial_year,
                net_revenue_gap: report.preliminary_summary.net_variance,
                total_approved_arr: report.preliminary_summary.total_approved_arr,
                total_actual_arr: report.preliminary_summary.total_actual_arr,
                controllable_gap: report.gap_analysis?.controllable_gap || 0,
                uncontrollable_gap: report.gap_analysis?.uncontrollable_gap || report.preliminary_summary.net_variance,
                anomaly_flags_count: report.anomaly_count || 0
            });
            setDraft(response.draft_narrative);
            setEditedDraft(response.draft_narrative);
            toast.success('AI Tariff Draft generated successfully');
        } catch (error) {
            toast.error('Failed to generate Tariff Draft via LLM');
            console.error(error);
        } finally {
            setLoading(false);
        }
    };

    const handleSave = () => {
        setDraft(editedDraft);
        setIsEditing(false);
        toast.success('Draft saved for final issuance.');
    };

    return (
        <div className="bg-white p-6 rounded-lg shadow mt-6 border-t-4 border-indigo-500">
            <div className="flex justify-between items-center mb-4">
                <div>
                    <h3 className="text-xl font-bold text-gray-800">LLM-Assisted Tariff Generation</h3>
                    <p className="text-sm text-gray-500">Translates the final Gap Analysis into a formal regulatory summary.</p>
                </div>
                {!draft && (
                    <button
                        onClick={handleGenerate}
                        disabled={loading}
                        className="px-4 py-2 bg-indigo-600 text-white rounded hover:bg-indigo-700 disabled:opacity-50"
                    >
                        {loading ? 'Generating...' : 'Generate AI Draft'}
                    </button>
                )}
            </div>

            {draft && (
                <div className="space-y-4">
                    <div className="bg-yellow-50 border-l-4 border-yellow-400 p-3">
                        <p className="text-sm text-yellow-800">
                            <strong>Human Review Required:</strong> This draft was generated by an AI assistant. Please review, edit, and approve before official issuance.
                        </p>
                    </div>

                    {isEditing ? (
                        <textarea
                            className="w-full h-48 p-3 border rounded text-sm font-serif"
                            value={editedDraft}
                            onChange={(e) => setEditedDraft(e.target.value)}
                        />
                    ) : (
                        <div className="p-4 bg-gray-50 border rounded whitespace-pre-wrap font-serif text-sm">
                            {draft}
                        </div>
                    )}

                    <div className="flex gap-2">
                        {isEditing ? (
                            <>
                                <button
                                    onClick={handleSave}
                                    className="px-4 py-2 bg-green-600 text-white rounded text-sm hover:bg-green-700"
                                >
                                    Save Edits
                                </button>
                                <button
                                    onClick={() => setIsEditing(false)}
                                    className="px-4 py-2 bg-gray-200 text-gray-700 rounded text-sm hover:bg-gray-300"
                                >
                                    Cancel
                                </button>
                            </>
                        ) : (
                            <button
                                onClick={() => setIsEditing(true)}
                                className="px-4 py-2 bg-blue-100 text-blue-700 rounded text-sm hover:bg-blue-200"
                            >
                                Edit Draft
                            </button>
                        )}
                    </div>
                </div>
            )}
        </div>
    );
}
